# Originated from https://github.com/csete/gpredict/pull/298
# Courtesy @NebulaOnion

name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  linuxbuild:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: dependencies
      run: |
        sudo apt update -qq
        sudo apt upgrade -y
        sudo apt install -y libtool intltool autoconf automake libcurl4-openssl-dev pkg-config libglib2.0-dev libgtk-3-dev libgoocanvas-2.0-dev
    - name: autogen
      run: ./autogen.sh
    - name: make
      run: make
    - name: make check
      run: make check
  win32build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
        working-directory: win32
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW32
          update: true
          install: base-devel git zip mingw-w64-i686-gcc mingw-w64-i686-toolchain mingw-w64-i686-gtk3 mingw-w64-i686-goocanvas
      - name: CIw32-Build
        run: | 
         make dist
      - uses: actions/upload-artifact@v3
        with:
          name: gpredict-win32
          path: ${{ github.workspace }}/win32/gpredict*.zip
  win64build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
        working-directory: win32
    steps:
      - uses: actions/checkout@v2
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: base-devel git zip mingw-w64-x86_64-gcc mingw-w64-x86_64-toolchain mingw-w64-x86_64-gtk3 mingw-w64-x86_64-goocanvas
      - name: CIw64-Build
        run: |
         make dist
      - uses: actions/upload-artifact@v3
        with:
          name: gpredict-win64
          path: ${{ github.workspace }}/win32/gpredict*.zip
